version: "2"
linters:
  default: all
  settings:
    varnamelen:
      ignore-names:
          - pt
  disable:
    # Disable by project
    - testpackage
    - depguard
    # Deprecated
    - wsl
    - gomodguard
