# =============================================================================
#  Docker Compose file for testing on Go versions 1.18 to the latest.
# =============================================================================
# It is recommended to run specifying a specific Go version and not at once.
#
# Since the service `tidy` will update/re-write the "go.mod" file to the latest
# module version, during it's process the "go.mod" file will be gone temporarily.
# Thus, `docker compose up` will cause failure in the other container because of
# missing "go.mod" file.
#
# - Recommended usage:
#   - To update go.mod:
#     $ docker compose run tidy
#   - To test:
#     $ docker compose run v1_18
#   - Lint check and static analysis:
#     $ docker compose run lint
# - NOT recommended to run all tests at once whith "up":
#     $ docker compose up
version: "3.9"

volumes:
  GO_PKG_MOD:

services:
  # Service tidy updates the go.mod to the latest
  tidy:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.22-alpine
    volumes:
      - .:/workspaces
    entrypoint: [ "./.github/run_go_mod_tidy.sh" ]
  # Run latest golangci-lint
  lint:
    image: golangci/golangci-lint:latest
    working_dir: /workspaces
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod
    entrypoint: [ "/usr/bin/golangci-lint",  "run", "--verbose" ]
  # Run code coverage
  cover:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod
    entrypoint: [ "./.github/run_go_test_cover.sh" ]
  # Service min runs the tests on minimum supported Go version
  min:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.22-alpine
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod
  # Service latest runs the tests on latest Go docker image
  latest:
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - .:/workspaces
      - GO_PKG_MOD:/go/pkg/mod